apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: journalapi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-2012966-journalapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journalapi
  template:
    metadata:
      labels:
        app: journalapi
    spec:
      containers:
        - name: journalapi
          image: docker.io/lmaofrankie96/journalapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/journalapi/instance
              name: instance-vol
        - name: nginx
          image: docker.io/lmaofrankie96/journalapi-nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: HOSTNAME
              value: project-2012966-pwp-deploy-tests.2.rahtiapp.fi
      volumes:
        - name: instance-vol
          persistentVolumeClaim:
            claimName: journalapi-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: project-2012966-journalapi
spec:
  type: NodePort
  selector:
    app: journalapi
  ports:
    - port: 8080
      targetPort: 8080
      
