apiVersion: v1
     kind: PersistentVolumeClaim
     metadata:
       name: journalapi-pvc
     spec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 32Mi
     ---
     apiVersion: apps/v1
     kind: Deployment
     metadata:
       name: journalapi-deployment
     spec:
       replicas: 1
       selector:
         matchLabels:
           app: journalapi
       template:
         metadata:
           labels:
             app: journalapi
         spec:
           containers:
             - name: journalapi
               image: docker.io/<your_dockerhub_username>/journalapi:latest
               imagePullPolicy: Always
               ports:
               - containerPort: 8000
                 protocol: TCP
               volumeMounts:
               - mountPath: /opt/journalapi/instance
                 name: instance-vol
             - name: nginx
               image: docker.io/<your_dockerhub_username>/journalapi-nginx:latest
               imagePullPolicy: Always
               ports:
               - containerPort: 8080
                 protocol: TCP
               env:
               - name: HOSTNAME
                 value: <your_group_name>-pwp-deploy-tests.2.rahtiapp.fi
           volumes:
           - name: instance-vol
             persistentVolumeClaim:
               claimName: journalapi-pvc
     ---
     apiVersion: v1
     kind: Service
     metadata:
       name: journalapi-entrypoint
       namespace: default
     spec:
       type: NodePort
       selector:
         app: journalapi
       ports:
         - port: 8080
           targetPort: 8080
           nodePort: 30001