version: '3.9'

services:
  journal-api:
    build: .
    container_name: journal-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
    environment:
      - DEBUG=False
      - SECRET_KEY=your_production_secret_key
      - DATABASE_URL=postgresql://journal_user:journal_pass@db:5432/journal_db
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: journal-db
    restart: always
    environment:
      POSTGRES_USER: journal_user
      POSTGRES_PASSWORD: journal_pass
      POSTGRES_DB: journal_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
